### ISSUE TITLE
Can I do an upgrade with this?

### ISSUE THREAD

**Issue by AceHack** [PowerShell/xDatabase#17]
DAC supports Db Upgrades https://technet.microsoft.com/en-us/library/ee634742(v=sql.130).aspx.  I'm curious if I can do that with your tools.  Thanks.

**Comment by GoEddie** [comment]
The link seems to have all the full stops removed but I guess you mean "Upgrade a Data-tier Application" (https://technet.microsoft.com/en-us/library/ee634742(v=sql130).aspx) :) - yes you can pass in a dacpac and have it upgrade a database
