### ISSUE TITLE
BLOCKER: PSSA Errors Need to Be Fixed

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xDatabase#24]
Errors from PS script analyzer are causing the tests to fail like [this](https://ci.appveyor.com/project/PowerShell/xdatabase/build/1.4.57.0).
This resource module cannot be released until these errors are fixed or suppressed and the tests are passing.

**Comment by GoEddie** [comment]
I have submitted a pr to the EditAppVeyorFile for this - the errors are for a sample file that gives an example of how to use the resource so added an ignore for them.

**Comment by kwirkykat** [comment]
Closed by #25
