### ISSUE TITLE
Error xDBPackage - The term 'CheckIfDbExists' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by dazinator** [PowerShell/xDatabase#36]
I am seeing the following error whilst attempting to use xDBPackage:

> VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/Des
iredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer PC023 with user sid xxx.
VERBOSE: [PC023]: LCM:  [ Start  Set      ]
VERBOSE: [PC023]: LCM:  [ Start  Resource ]  [[xDBPackage]ExtractBacPac]
VERBOSE: [PC023]: LCM:  [ Start  Test     ]  [[xDBPackage]ExtractBacPac]
You cannot call a method on a null-valued expression.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : InvokeMethodOnNull
    + PSComputerName        : localhost
 
> The term 'CheckIfDbExists' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
    + CategoryInfo          : ObjectNotFound: (CheckIfDbExists:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost
 
> VERBOSE: [PC023]: LCM:  [ End    Test     ]  [[xDBPackage]ExtractBacPac]  in 1.1580 seconds.
The PowerShell DSC resource '[xDBPackage]ExtractBacPac' with SourceInfo 'C:\Users\xxx\Desktop\Bobv2 sample\extractbob.ps1::28::9::xDBPackage' threw one or more non-terminating errors while 
running the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
> VERBOSE: [PC023]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
> VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.742 seconds

**Comment by johlju** [comment]
Can you provide the configuration you are using when you get this error?
