### ISSUE TITLE
Unable to find Dac tools on 2016 Marketplace Azure images

### ISSUE THREAD

**Issue by adhodgson1** [PowerShell/xDatabase#37]
Hi,

The DSC resource is unable to find the Dac resources on a 2016 SQL Azure marketplace image because a newer version of the management tools are installed and this puts the files in 140\dac instead of 130\dac.

Ideally we need a construct to allow the SQL Server 2017 to be used in the script and the workaround would then be to use the 2017 version on the machines that had 2016 deployed from the marketplace images.

**Comment by johlju** [comment]
This was resolved in PR #38.
