### ISSUE TITLE
Not able to perform Windows SSPI authentication

### ISSUE THREAD

**Issue by ahmedgillanione** [PowerShell/xDatabase#5]
Can you please provide sample params to create new database using SSPI windows authentication.

Documentation says if Credentials property is not passed as set then it will automatically create to SSPI of Powershell calling code to use windows authention.

but Test and Set Target source functions start complaining if you dont pass them.

I manualy modified the MSFT_xDatabase poweshell module inside xDatabase folder to hard code windows SSPI and it worked by disabling SQL mode connection string.

thanks in advance for any suggestion.

**Comment by GoEddie** [comment]
I used this and it works fine just make sure you don't specify anything for the credentials:

Node 'Machine'
    {

```
    xDatabase DeployDac
    {
        Ensure = $Ensure
        SqlServer = $SqlServer
        SqlServerVersion = $SqlServerVersion
        DatabaseName = $DatabaseName
        DacPacPath =  $DacPacPath
        DacPacApplicationName = $DacPacApplicationName

    }
}
```

Looking at the code if you have this then it will set the connection string to use SSPI instead of sql authentication.
